apiVersion: signadot.com/v1
kind: Sandbox
name: temporal-worker-sb
spec:
   description: Isolated sandbox environments to enable transparent workflow versioning
   cluster: "@{cluster}"
   forks:
   - forkOf:
       kind: Deployment
       name: temporal-worker-baseline
       namespace: temporal
     customizations:
       images:
        - image: asia-docker.pkg.dev/itone-295207/casino-backend/temporal-money-transfer:sandbox
       env:
        - name: SANDBOX_NAME
          value: "temporal-worker-sb"